version: "3.8"
services:
  dagster:
    container_name: dagster
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - "./logs:/var/logs/dagster"
      - "./pipelines:/opt/dagster/pipelines"
    networks:
      - dagster
networks:
  dagster:
